"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](osbadge)\
$os\
$username\
[](bg:whbadge fg:osbadge)\
$directory\
[](fg:whbadge bg:gitbadge)\
$git_branch\
$git_status\
[](fg:gitbadge bg:blue)\
$rust\
$golang\
$nodejs\
$python\
[](fg:blue bg:teal)\
$docker_context\
[](fg:teal bg:timebadge)\
$time\
[ ](fg:timebadge)\
$line_break$character"""

palette = 'vaporize'

[palettes.vaporize]
osbadge = "#3B24F3"
ostext = "#47d5fc"
whbadge = "#9112c7"
whtext = "#e0a2c8"
gitbadge = "#cf3659"
gittext = "#03000d"
teal="#13d5eb"
blue="#012d73"
base="#ceebea"
timebadge = "#0ee6b3"
timetext = "#154a20"

[os]
disabled = false
style = "bg:osbadge fg:ostext"

[os.symbols]
Windows = "󰍲"
Ubuntu = " 󰄛 "
Macos = ""
Linux = "󰌽"
Gentoo = "󰣨"
Amazon = ""
Arch = "󰣇"
Debian = "󰣚"

[username]
show_always = true
style_user = "bg:osbadge fg:ostext"
style_root = "bg:osbadge fg:ostext"
format = '[ $user ]($style)'

[directory]
style = "fg:whtext bg:whbadge"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = " "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"git" = " " 
"~"=""
"project_orion"=" "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:gittext bg:gitbadge)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:gittext bg:gitbadge)]($style)'

[nodejs]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[rust]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[golang]
symbol = "󰨉 "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[python]
symbol = "󱔎 "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[docker_context]
symbol = " "
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:timetext"
format = '[[  $time ](fg:timetext bg:timebadge)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
